# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- main
- dev

pool: Default

variables:
  buildConfiguration: 'Release'
  Major: '1'
  Minor: '1'
  revision: $[counter(variables['Minor'], 1)]
  nugetVersion: '$(Major).$(Minor).$(revision)'
  nugetProjectName: 'ConsoleApp1'

jobs:
- job: mainPipe
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))

  steps:
  - task: DotNetCoreCLI@2
    displayName: Restore
    inputs:
      command: 'restore'
      projects: '**/*.csproj'

  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      command: 'build'
      projects: '**/*.csproj'
      arguments: '--configuration $(buildConfiguration)'

  - task: DotNetCoreCLI@2
    displayName: 'Pack the project into a NuGet package'
    inputs:
      command: 'pack'
      packagesToPack: '**/*.csproj'
      configuration: $(buildConfiguration)
      outputDir: '$(Build.ArtifactStagingDirectory)'
      versioningScheme: 'byEnvVar'
      versionEnvVar: 'nugetVersion'

  - task: NuGetCommand@2
    inputs:
      command: 'push'
      packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
      nuGetFeedType: 'internal'
      publishVstsFeed: 'a573a66d-a331-4b5b-89e5-37ce46c0521e/0d56472f-3fa6-4d01-b75f-dc8c1c705b8a'

      
  - task: DotNetCoreCLI@2
    inputs:
      command: 'push'
      packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
      nuGetFeedType: 'internal'
      publishVstsFeed: 'a573a66d-a331-4b5b-89e5-37ce46c0521e/755ba64a-01e8-41bb-8970-0edb41a61e72'


- job: devPipe
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/dev'))
  
  steps:
  - task: SonarQubePrepare@6
    inputs:
      SonarQube: 'sonarQube-azure-pipeline'
      scannerMode: 'MSBuild'
      projectKey: 'HelloWorld_HelloWorld_AZAgj76P8F9AytLPHiAo'
  
  - task: SonarQubeAnalyze@6
    inputs:
      jdkversion: 'JAVA_HOME_17_X64'

  - task: SonarQubePublish@6
    inputs:
      pollingTimeoutSec: '300'

