# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- main

pool: Default

variables:
  buildConfiguration: 'Release'
  BuildNumberFormat: '$(BuildDefinitionName)_$(Year:yyyy).$(Month).$(DayOfMonth)$(Rev:.r).'
  BUILD_BUILDNUMBER: '$(BuildNumberFormat)'
  Major: '1'
  Minor: '0'
  revision: $[counter(variables['Mainor'], 1)]
  nugetVersion: '$(Major).$(Minor).$(revision)'
  nugetProjectName: 'ConsoleApp1'

steps:
- task: NuGetToolInstaller@1
  inputs:
    versionSpec: '5.5.1'
    checkLatest: true

- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: 'restore'
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Pack the project into a NuGet package'
  inputs:
    command: 'pack'
    packagesToPack: '**/*.csproj'
    configuration: $(buildConfiguration)
    outputDir: '$(Build.ArtifactStagingDirectory)'

- task: NuGetCommand@2
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: 'a573a66d-a331-4b5b-89e5-37ce46c0521e/0d56472f-3fa6-4d01-b75f-dc8c1c705b8a'
    allowPackageConflicts: true